
import { APP_API_BASE_URL, APP_API_ATTENDANCE_URL,APP_BG_COLOR } from '@env';

export const API_BASE_URL = APP_API_BASE_URL;
export const API_ATTENDANCE_URL = APP_API_ATTENDANCE_URL;
export const APP_BACKGROUND_COLOR = APP_BG_COLOR
